(function () {
  if (!localStorage.getItem("ecommerceData")) {
    console.log("Initializing E-commerce data in localStorage...");
  
    const data = {
      users: [
        {
          id: 1,
          name: "Admin User",
          email: "admin@example.com",
          password: "admin123",
          role: "admin",
          joinedDate: "2024-05-12",
        },
        {
          id: 2,
          name: "Seller One",
          email: "seller1@example.com",
          password: "seller123",
          role: "seller",
          joinedDate: "2024-07-01",
        },
        {
          id: 3,
          name: "John Doe",
          email: "john@example.com",
          password: "customer123",
          role: "customer",
          joinedDate: "2024-08-15",
        },
      ],
      products: [
        // Men's Fashion
        {
          id: 1,
          name: "Men's Leather Jacket",
          category: "Men's Fashion",
          price: 120,
          discount: 15,
          stock: 25,
          soldCount: 10,
          description: "Stylish black leather jacket.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },
        {
          id: 2,
          name: "Men's Sneakers",
          category: "Men's Fashion",
          price: 60,
          discount: 10,
          stock: 50,
          soldCount: 20,
          description: "Comfortable everyday sneakers.",
          imageUrl: "shoes.png",
          sellerId: 2,
        },
        {
          id: 3,
          name: "Men's Formal Shirt",
          category: "Men's Fashion",
          price: 35,
          discount: 0,
          stock: 70,
          soldCount: 30,
          description: "Classic white formal shirt.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },
        {
          id: 4,
          name: "Men's Jeans",
          category: "Men's Fashion",
          price: 45,
          discount: 5,
          stock: 40,
          soldCount: 15,
          description: "Blue slim-fit jeans.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },
        {
          id: 5,
          name: "Men's Hoodie",
          category: "Men's Fashion",
          price: 50,
          discount: 12,
          stock: 30,
          soldCount: 12,
          description: "Casual grey hoodie.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },

        // Women's Fashion
        {
          id: 6,
          name: "Women's Summer Dress",
          category: "Women's Fashion",
          price: 40,
          discount: 10,
          stock: 45,
          soldCount: 20,
          description: "Floral print summer dress.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },
        {
          id: 7,
          name: "Women's Handbag",
          category: "Women's Fashion",
          price: 80,
          discount: 5,
          stock: 35,
          soldCount: 15,
          description: "Elegant leather handbag.",
          imageUrl: "jacket2.png",
          sellerId: 2,
        },
        {
          id: 8,
          name: "Women's Heels",
          category: "Women's Fashion",
          price: 55,
          discount: 0,
          stock: 25,
          soldCount: 10,
          description: "Red high heels.",
          imageUrl: "jacket2.png",
          sellerId: 2,
        },
        {
          id: 9,
          name: "Women's Blouse",
          category: "Women's Fashion",
          price: 30,
          discount: 8,
          stock: 50,
          soldCount: 18,
          description: "Silk white blouse.",
          imageUrl: "jacket2.png",
          sellerId: 2,
        },
        {
          id: 10,
          name: "Women's Jeans",
          category: "Women's Fashion",
          price: 45,
          discount: 10,
          stock: 40,
          soldCount: 17,
          description: "Skinny blue jeans.",
          imageUrl: "jacket2.png",
          sellerId: 2,
        },

        // Electronics
        {
          id: 11,
          name: "Speaker LGT",
          category: "Electronics",
          price: 500,
          discount: 15,
          stock: 20,
          soldCount: 8,
          description: "A cool speaker with lights.",
          imageUrl: "speaker.png",
          sellerId: 2,
        },
        {
          id: 12,
          name: "Laptop Pro 15",
          category: "Electronics",
          price: 1200,
          discount: 20,
          stock: 15,
          soldCount: 5,
          description: "High-performance laptop.",
          imageUrl: "laptop.png",
          sellerId: 2,
        },
        {
          id: 13,
          name: "Playstation",
          category: "Electronics",
          price: 80,
          discount: 5,
          stock: 60,
          soldCount: 25,
          description: "Noise-cancelling earbuds.",
          imageUrl: "playstation.png",
          sellerId: 2,
        },
        {
          id: 14,
          name: "Modern Keyboard",
          category: "Electronics",
          price: 200,
          discount: 10,
          stock: 35,
          soldCount: 15,
          description: "Keyboard with rgp Lights.",
          imageUrl: "keyboard.png",
          sellerId: 2,
        },
        {
          id: 15,
          name: "Bluetooth Speaker",
          category: "Electronics",
          price: 90,
          discount: 8,
          stock: 40,
          soldCount: 18,
          description: "Portable speaker with deep bass.",
          imageUrl: "speaker2.png",
          sellerId: 2,
        },

        // Furniture
        {
          id: 16,
          name: "Table with shilves",
          category: "Furniture",
          price: 350,
          discount: 12,
          stock: 10,
          soldCount: 3,
          description: "A table that has shalves to organise your books.",
          imageUrl: "table.png",
          sellerId: 2,
        },
        {
          id: 17,
          name: " Chair",
          category: "Furniture",
          price: 150,
          discount: 10,
          stock: 25,
          soldCount: 10,
          description: "A relaxing chair.",
          imageUrl: "chair.png",
          sellerId: 2,
        },
        {
          id: 18,
          name: "Sofa Set",
          category: "Furniture",
          price: 800,
          discount: 18,
          stock: 5,
          soldCount: 2,
          description: "Luxury 3-piece sofa set.",
          imageUrl: "table.png",
          sellerId: 2,
        },
        {
          id: 19,
          name: "Bed Frame",
          category: "Furniture",
          price: 400,
          discount: 15,
          stock: 8,
          soldCount: 3,
          description: "Queen-size bed frame.",
          imageUrl: "chair.png",
          sellerId: 2,
        },
        {
          id: 20,
          name: "Bookshelf",
          category: "Furniture",
          price: 120,
          discount: 0,
          stock: 12,
          soldCount: 5,
          description: "5-tier wooden bookshelf.",
          imageUrl: "table.png",
          sellerId: 2,
        },

        // Toys
        {
          id: 22,
          name: "Remote Control Car",
          category: "Toys",
          price: 50,
          discount: 10,
          stock: 40,
          soldCount: 18,
          description: "Fast RC car with rechargeable battery.",
          imageUrl: "toy.png",
          sellerId: 2,
        },
        
        //Electronics again
        {
          id: 21,
          name: "Controller",
          category: "Electronics",
          price: 70,
          discount: 5,
          stock: 30,
          soldCount: 12,
          description: "A modern Controller for your Games.",
          imageUrl: "controller2.png",
          sellerId: 2,
        },

        {
          id: 23,
          name: "Camera",
          category: "Electronics",
          price: 90,
          discount: 8,
          stock: 15,
          soldCount: 6,
          description: "Modern Camera with high resulations.",
          imageUrl: "camera.png",
          sellerId: 2,
        },
        {
          id: 24,
          name: "Controller",
          category: "Electronics",
          price: 25,
          discount: 0,
          stock: 50,
          soldCount: 20,
          description: "A black Controller.",
          imageUrl: "controller2.png",
          sellerId: 2,
        },
        {
          id: 25,
          name: "Speaker high tech",
          category: "Electronics",
          price: 35,
          discount: 5,
          stock: 45,
          soldCount: 15,
          description: "A high Tech Speaker.",
          imageUrl: "speaker3.png",
          sellerId: 2,
        },

        // Extra products to reach 30+
        {
          id: 26,
          name: "Men's Watch",
          category: "Men's Fashion",
          price: 150,
          discount: 10,
          stock: 20,
          soldCount: 8,
          description: "Luxury analog watch.",
          imageUrl: "jacket.png",
          sellerId: 2,
        },
        {
          id: 27,
          name: "bag",
          category: "Women's Fashion",
          price: 120,
          discount: 15,
          stock: 18,
          soldCount: 7,
          description: "Gold-plated bag.",
          imageUrl: "bag.png",
          sellerId: 2,
        },
        {
          id: 28,
          name: "TV",
          category: "Electronics",
          price: 350,
          discount: 12,
          stock: 25,
          soldCount: 9,
          description: "A Modern Slim TV.",
          imageUrl: "tv.png",
          sellerId: 2,
        },
        {
          id: 29,
          name: "Recliner Chair",
          category: "Furniture",
          price: 500,
          discount: 20,
          stock: 6,
          soldCount: 2,
          description: "Comfortable recliner chair.",
          imageUrl: "chair.png",
          sellerId: 2,
        },
        {
          id: 30,
          name: "Board Game",
          category: "Toys",
          price: 40,
          discount: 8,
          stock: 35,
          soldCount: 14,
          description: "Family board game set.",
          imageUrl: "toy.png",
          sellerId: 2,
        },
        {
          id: 31,
          name: "Red Car",
          category: "Toys",
          price: 50,
          discount: 10,
          stock: 40,
          soldCount: 18,
          description: "Fast RC car with rechargeable battery.",
          imageUrl: "toy.png",
          sellerId: 2,
        },
        {
          id: 32,
          name: "Racing Car",
          category: "Toys",
          price: 50,
          discount: 10,
          stock: 40,
          soldCount: 18,
          description: "Fast RC car with rechargeable battery.",
          imageUrl: "toy.png",
          sellerId: 2,
        },
      ],
      cart: [
        {
          userId: 3,
          items: [
            { productId: 2, quantity: 1 },
            { productId: 11, quantity: 1 },
          ],
        },
      ],
      wishlist: [{ userId: 3, productIds: [6, 13, 21] }],
      orders: [
        {
          orderId: 101,
          userId: 3,
          items: [
            { productId: 1, quantity: 1, priceAtPurchase: 102 },
            { productId: 6, quantity: 1, priceAtPurchase: 36 },
          ],
          totalAmount: 138,
          status: "Delivered",
          orderDate: "2025-08-10",
        },
      ],
    };
    localStorage.setItem("ecommerceData", JSON.stringify(data));
  }
   else {
    console.log("E-commerce data already exists in localStorage.");
  }
})();
